export { default as Titles } from './Titles';
export { default as Header } from './Header';
export { default as Banner } from './Banner';
export { default as Work } from './Work';
export { default as AboutMeHome } from './AboutMeHome';
export { default as Services } from './Services';
export { default as Testimonials } from './Testimonials';
export { default as ProjectSummary } from './ProjectSummary';
export { default as TeamMembers} from './TeamMembers';
export { default as ResearchInsights } from './ResearchInsights';
export { default as Design } from './Design'; 
export { default as AboutMeBanner } from './AboutMeBanner';
export { default as EduWork } from './EduWork'; 
export { default as Featledge } from './Featledge';
export { default as LicensesList } from './LicensesList';
export { default as Footer } from './Footer';
